// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaTurnoApi.Models;

namespace SistemaTurnoApi.Migrations
{
    [DbContext(typeof(TurnQueueDb))]
    partial class TurnQueueDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaTurnoApi.Models.Queue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QueueName")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("TimeAttention")
                        .HasColumnType("int");

                    b.HasKey("QueueId");

                    b.ToTable("Queues");

                    b.HasData(
                        new
                        {
                            QueueId = 1,
                            QueueName = "Cola 1",
                            TimeAttention = 2
                        },
                        new
                        {
                            QueueId = 2,
                            QueueName = "Cola 2",
                            TimeAttention = 3
                        });
                });

            modelBuilder.Entity("SistemaTurnoApi.Models.Turn", b =>
                {
                    b.Property<int>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HourAttention")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PersonId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PersonName")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("QueueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(10)");

                    b.HasKey("TurnId");

                    b.HasIndex("QueueId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("SistemaTurnoApi.Models.Turn", b =>
                {
                    b.HasOne("SistemaTurnoApi.Models.Queue", "Queue")
                        .WithMany("Turns")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("SistemaTurnoApi.Models.Queue", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
